import { test, expect } from "@playwright/test";

test('Codigng -> Click on Register button, validate errors, Reload page, validate errors not visible',
    async ({ page }) => {

        await page.goto('/');

        const msgs = page.locator('.invalid-feedback');

        await page.getByRole('button', { name: 'Register' }).click();
        await expect(msgs).toHaveCount(3);
        for(const msg of await msgs.all()) {
            await expect(msg).toBeVisible();
        }

        await page.reload()
        for(const msg of await msgs.all()) {
            await expect(msg).toBeHidden();
        }
    }
);

/**
 * Scenario generated by copilot
 */
test('Copilot -> Abrir un navegador, click en el boton Register, validar que los mensajes de error sean visibles, recargar la pagina, validar que los mensajes de error no sean visibles',
    async ({ page }) => {
        await page.goto('/');

        const errorMessages = page.locator('.invalid-feedback');

        await page.getByRole('button', { name: 'Register' }).click();
        await expect(errorMessages).toHaveCount(3);
        for (const message of await errorMessages.all()) {
            await expect(message).toBeVisible();
        }

        await page.reload();
        for (const message of await errorMessages.all()) {
            await expect(message).toBeHidden();
        }
    }
);

/**
 * Scenario generated by Claude, different approach
 */
test('Claude -> Abrir un navegador, click en el boton Register, validar que los mensajes de error sean visibles, recargar la pagina, validar que los mensajes de error no sean visibles',
    async ({ page }) => {
        await page.goto('/');

        const firstNameError = page.getByText('Valid first name is required');
        const lastNameError = page.getByText('Valid last name is required');
        const emailError = page.getByText('Please enter a valid email address');
        const visibleErrors = page.locator('.invalid-feedback').filter({ visible: true });

        await page.getByRole('button', { name: 'Register' }).click();
        await expect(firstNameError).toBeVisible();
        await expect(lastNameError).toBeVisible();
        await expect(emailError).toBeVisible();
        await expect(visibleErrors).toHaveCount(3);

        await page.reload();
        await expect(firstNameError).toBeHidden();
        await expect(lastNameError).toBeHidden();
        await expect(emailError).toBeHidden();
        await expect(visibleErrors).toHaveCount(0);
    }
);